---
kind: pipeline
type: ssh
name: default

server:
  host:
    from_secret: HOST_ADDR
  user:
    from_secret: USER
  password:
    from_secret: PASSWORD

steps:
- name: test
  commands:
  - sudo docker-compose -f docker-compose-prod.yml up -d --build --force-recreate
